server:
  http:
    addr: 0.0.0.0:${HTTP_PORT:8000}
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    dsn: root:root@tcp(172.23.80.1:3306)/db2?parseTime=True&loc=Local&charset=utf8mb4
  redis:
    addr: 172.23.80.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
mode: dev
token:
    accessToken:
      accessSecret: "夏天夏天悄悄过去"
      accessExpire: 60
    refreshToken:
      refreshSecret: "冬天冬天悄悄来临"
      refreshExpire: 120

